# Generated by Django 5.1 on 2024-08-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_blog_post_publish_bb7600_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
